name: lightning
description: A sample web application
dependencies:
  angular: any
  browser: any
  google_maps: any
  intl: any
  jsonx: 1.2.7
  logging: any
  unittest: any
  web_components: any
transformers:
- angular
