name: lightning
description: A sample web application
dependencies:
  web_components: any
  angular: 0.13.0
  browser: any
  intl: any
  jsonx: 1.2.7
  logging: any
  unittest: any
transformers:
- angular
